### ISSUE TITLE
Automatically submit form when you click "select all"

### ISSUE THREAD

**Issue by gavinr** [raykendo/Map-Services-Enhanced#8]
I often click `select all` and then have to scroll down and press "query (GET)". to reduce button clicks for this common workflow, i'd prefer either of the follwowing:

1. Have the chrome plugin auto-fill `where:1=1` and `outFields:*` when you get to the page by default (if there are not any pre-filled values from a previous search). Then i only have to click one button on the page ("Query GET")
2. When I click `Select All` button, fill the form and automatically submit the form for me.

**Comment by raykendo** [comment]
Just published a new version to the Chrome store with this option. The buttons *Select All*, *Select all but Geometry*, and *Get Count Only* will trigger this selection. 

You can set whether these buttons trigger a Get request, post request, or nothing in the options page for the tool.

**Comment by gavinr** [comment]
nice! Thanks @raykendo! looking forward to checking it out.
