### ISSUE TITLE
[Feature Request] - URL Shortener

### ISSUE THREAD

**Issue by jpeterson** [raykendo/Map-Services-Enhanced#9]
### Feature
A “Map/Feature Service Query URL shortener”.

### Use Case
I often want to share a query url with someone, but, when clicking **Query (GET)**, the REST page adds every possible parameter to the url, resulting in something like this:
>http://sampleserver6.arcgisonline.com/arcgis/rest/services/Census/MapServer/3/query?where=MED_AGE+%3C33&text=&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&relationParam=&outFields=*&returnGeometry=true&returnTrueCurves=false&maxAllowableOffset=&geometryPrecision=&outSR=&returnIdsOnly=false&returnCountOnly=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&returnZ=false&returnM=false&gdbVersion=&returnDistinctValues=false&resultOffset=&resultRecordCount=&f=html

Which could be shortened to this:
>http://sampleserver6.arcgisonline.com/arcgis/rest/services/Census/MapServer/3/query?where=MED_AGE+%3C33&returnGeometry=false

It would be awesome if I could share shorter, more comprehensible urls like the latter example above, perhaps by clicking a button in this extension's UI.

**Comment by raykendo** [comment]
This feature has been added to the 1.2.0 version of the application, and can be accessed by clicking on the Map Services Enhanced icon. If the URL can be shortened, a text box will appear that will display the shortened URL link, along with a copy to clipboard button.

For your example, I did leave the outFields=* in the results. I don't always trust that the query will go through without something in the outFields.
